#------------------ 数据源配置 -----------------#
spring:
  datasource:
    url: jdbc:h2:~/test #数据库地址
    driver-class-name: org.h2.Driver #数据库驱动
    username: sa #用户名
    password: 123456 #密码
  jpa:
    datasource: h2 #数据库类型
    hibernate:
      ddl-auto: create-drop #启动后自动创建数据库表,服务器关闭时自动删除创建的表
    show-sql: true #控制台打印sql
  h2:
    console:
      path: /h2-console #h2数据库控制台地址
      enabled: true #启用
#------------------ 数据源配置 -----------------#