spring:
  datasource:
    url: jdbc:h2:~/test
    driver-class-name: org.h2.Driver
    username: sa
    password: 123456

  jpa:
    datasource: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      path: /h2-console
      enabled: true